baseURL = 'https://alinblue.github.io/mi_primera_web/public/'
languageCode = 'es-es'
title = 'My New Hugo Site'
theme="terminal"

ignoreLogs= ['warning-goldmark-raw-html']
[markup.goldmark.renderer]
unsafe = true